# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # The following dependencies should match the package inside the camunda modeler for best compatibility.
      # After the Camunda Modeler issue 4511 is resolved, these dependencies can be removed entirely from this package.
      # See: https://github.com/camunda/camunda-modeler/issues/4511
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-is"
      - dependency-name: "@carbon/react"
      - dependency-name: "@carbon/icons-react"
