name: Continuous Integration

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

jobs:
  verify-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npx nx run-many -t lint

  verify-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      # later we should run our test suite here
      - run: npx nx run-many -t build

  create-plugin-artifacts:
    needs:
      - "verify-lint"
      - "verify-tests"
    
    permissions:
      contents: write

    uses: ./.github/workflows/create-plugin-artifacts.yml
    with:
      ref: ${{ github.sha }}
      tag: ${{ github.ref_name }}
      retention-days: ${{ github.retention_days }}
      overwrite: true
