name: Create plugin artifacts

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      retention-days:
        type:  number
        default: 1
      overwrite:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
        ref:
          type: string
          required: true
        retention-days:
          type:  number
          default: 1
        overwrite:
          type: boolean
          default: false

concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

jobs:
  collect-plugins:
    runs-on: ubuntu-latest
    outputs:
      plugins: ${{ steps.collect-plugins.outputs.plugins }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - id: collect-plugins
        run: echo "plugins=$(npx nx show projects --with-target pack-plugin --json)" >> $GITHUB_OUTPUT


  create-plugin-artifacts:
    needs:
      - "collect-plugins"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ${{ fromJson(needs.collect-plugins.outputs.plugins) }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: echo "PLUGIN_NAME=$(node -p '"${{ matrix.plugin }}".replace("@", "").replace("/", "-")')"
      - run: echo "PACK_NAME=$(node -p '"${{ env.PLUGIN_NAME }}-${{ inputs.ref }}".replace("/", "-")')" >> $GITHUB_ENV
      - run: npx nx pack-plugin ${{ matrix.plugin }} --args="--source {projectRoot} --destination packs --file-name ${{ env.PACK_NAME }}"
      - run: unzip "packs/${{ env.PACK_NAME }}.zip" -d "packs/${{ env.PACK_NAME }}"

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PACK_NAME }}"
          path: "packs/${{ env.PACK_NAME }}"
          retention-days: ${{ inputs.retention-days }}
          overwrite: ${{ inputs.overwrite }}
