name: Publish package to Github Packages

on:
  release:
    types: [created]

jobs:
  verify-build:
    uses: ./.github/workflows/build-package.yml

  publish-github-packages:
    needs: verify-build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm ci --workspaces
      - run: npm run build
      - run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
