name: Publish a release

on:
  push:
    tags:
      # Matches tags that have the shape `vX.Y.Z`
      # Reference: https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npx nx run-many -t pack-plugin --args="--source {projectRoot} --destination packs"
  
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          artifacts: "./packs/*.zip"
          artifactErrorsFailBuild: true

  publish-github-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npx nx run-many -t build
      - run: npx nx release publish --registry "https://npm.pkg.github.com/" --exclude "@camunda-modeler-code-editor@root"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npx nx run-many -t build
      - run: npx nx release publish --registry "https://registry.npmjs.org/" --exclude "@camunda-modeler-code-editor@root"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

