name: Release a version

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref'
        type: string
        default: 'main'
      version:
        description: 'Version'
        type: string
        required: true

jobs:
  release-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: npx nx release version --specifier ${{ inputs.version }}

