name: Verify pull requests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-lint:
    uses: ./.github/workflows/lint-package.yml

  verify-build:
    uses: ./.github/workflows/build-package.yml
